[workspace]
members = [
	"primitives",
	"runtimes/common"
]

[profile.release]
# Astar runtime requires unwinding.
panic = "unwind"

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
