[workspace]
members = [
	"node",
	"primitives",
	"runtimes/common",
	"runtimes/indranet",
]

[profile.release]
# Selendra runtime requires unwinding.
panic = "unwind"

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
