[workspace]
members = [
	# "node",
	"primitives",
	"runtime/common",
	"runtime/indranet",
]

[profile.release]
# Selendra runtime requires unwinding.
panic = "unwind"

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
